### ISSUE TITLE
Can't view injected styles in Dev Tools

### ISSUE THREAD

**Issue by joeshub** [rtsao/styletron#101]
When I click on the rule in Dev tools, the injected style tag has no visible content.

I can't seem to find if this is just me, expected behavior, or a bug.
Any idea what is causing this?

<img width="725" alt="screen shot 2017-03-11 at 12 23 42 pm" src="https://cloud.githubusercontent.com/assets/764006/23825778/b980fbb2-0655-11e7-99fd-5cf728e1017a.png">

**Comment by rtsao** [comment]
The styles aren't visible as text content of the stylesheet elements because styles are added via the JavaScript [`CSSStyleSheet.insertRule()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) API. It's done this way because adding styles via this method is drastically faster than appending text nodes and doesn't trigger a re-parse of the entire stylesheet.

You can access the styles via `styleElement.sheet.cssRules`.

**Comment by joeshub** [comment]
Ah thanks for the explanation @rtsao I'm glad I asked. Totally makes sense with Styletron being all about performance. I wonder why other frameworks don't bother with this approach as well. Might be due to dev ex I suppose. 

p.s. this might be a good item to for the README
