### ISSUE TITLE
Cannot install dependencies with Yarn where `test-fixtures` is used

### ISSUE THREAD

**Issue by faddee** [rtsao/styletron#131]
The package `test-fixtures` seems to be removed and causes this using Yarn in e.g. `packages/styletron-client`:

```
warning test-fixtures@1.0.0: Please don't use this, it will be removed soon.
error test-fixtures@1.0.0: The engine "node" is incompatible with this module. Expected version "~0.10.20".
```

**Comment by rtsao** [comment]
Is this when when actually installing `styletron-client` as a dependency or just when installing the monorepo?

It's interesting it's complaining about `test-fixtures@1.0.0` since the package version in the monorepo is `0.0.1.`, so I'm assuming it's not bootstrapping correctly. I suspect dropping the asterisk in favor of an explicit version should fix this.
