### ISSUE TITLE
Styletron rendering vs JSS

### ISSUE THREAD

**Issue by kof** [rtsao/styletron#17]
Maybe I oversee something, but it seems like you trying to replicate most of JSS + an API on top. Please correct me if I am wrong.

Is there anything in rendering this project does and JSS can't? 

Regarding the syntax sugar, I am also planing to add glamor like and styled-components as a higher level API's.

**Comment by rtsao** [comment]
Styletron obviously similar to Glamor, Aphrodite, Fela, and JSS, etc. in that it renders CSS but it has a radically different implementation and somewhat different goals and scope than alternatives, including a focus on supporting server-rendering use-cases and performance.

For example, Styletron generates "atomic CSS" and as a result has much smaller output than JSS (or glamor or aphrodite for that matter) because there's declaration-level deduplication of styles (similar to how static, server-side styles work in react-native-web). The actual core of Styletron is much lower-level API than alternatives, so a variety of APIs could be built on top.

I discuss this in https://github.com/necolas/react-native-web/issues/145 but the actual concept was pioneered in react-native-web StyleSheets. Though unlike react-native-web, Styletron works both on server and client (to support even runtime deduplication) and added support for psuedo selectors and media queries. Anyways, I hope this helps -- feel free to dig into the Styletron implementation and see how it works 😄.

**Comment by scott113341** [comment]
@rtsao, it might be beneficial if the "Server-side rendering" section of the readme showed the result of `render()` to illustrate how the deduplicated/critical CSS works.

**Comment by kof** [comment]
>  it has a radically different implementation

Can you please point me to the DOM rendering where it is radically different? I couldn't find.

> For example, Styletron generates "atomic CSS"

In other words, you you check if a rule decl user passed already exist and you just don't render it again, right?

> The actual core of Styletron is much lower-level API than alternatives, so a variety of APIs could be built on top.

That is what I also always say about JSS))) It is designed to support all low level approaches. And gets right now even better.

**Comment by kof** [comment]
> , including a focus on supporting server-rendering use-cases and performance.

Same for JSS, do you care to add styletron to this bench https://github.com/hellofresh/css-in-js-perf-tests ?

**Comment by kof** [comment]
All in all I don't see any other goals than what JSS does, styletron could be implemented as sugar + optimizations on top of JSS. Same like I did with Aphrodite https://github.com/cssinjs/aphrodisiac

**Comment by hville** [comment]
@kof the small size of styletron is also a feature. JSS is 10x bigger and adding things on top would only add to the weight,
