### ISSUE TITLE
Make stylesheet(s) optional in StyletronClient constructor

### ISSUE THREAD

**Issue by sammkj** [rtsao/styletron#22]
Here's what I did:

```
import React from 'react';
import ReactDOM from 'react-dom';
import Styletron from 'styletron';
import { StyletronProvider } from 'styletron-react';
import App from './App';
import './index.css';

const styletron = new Styletron(document.getElementsByClassName('styletron'));

ReactDOM.render(
  <StyletronProvider styletron={styletron}>
    <App/>
  </StyletronProvider>,
  document.getElementById('root')
);
```

and the rest is the same as CRA. I keep getting error below:

```
Uncaught TypeError: Cannot read property 'sheet' of undefined
    at StyletronClient.injectDeclaration (styletron-client.js:92)
    at injectWithPlugins (inject-style-prefixed.js:89)
    at Object.injectStyle [as injectStylePrefixed] (inject-style-prefixed.js:46)
    at StyledElement (styled.js:77)
    at ReactCompositeComponent.js:306
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:305)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:280)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:188)
    at Object.mountComponent (ReactReconciler.js:46)
```

**Comment by scott113341** [comment]
Hi @sammkj, do you have an HTML stylesheet element that matches `document.getElementsByClassName('styletron')`?  My guess is that returns `undefined`, which is why you're seeing the error.

Normally, the argument into the `Styletron` [constructor](http://styletron.js.org/StyletronClient.html) is an HTML `style` element that contains server-rendered styles that are used to hydrate the client's CSS cache.  If you're not using server rendering for Styletron, you could do something like this:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import Styletron from 'styletron';
import { StyletronProvider } from 'styletron-react';
import App from './App';
import './index.css';

const styleSheet = document.createElement('style');
document.head.appendChild(styleSheet);
const styletron = new Styletron(styleSheet);

ReactDOM.render(
  <StyletronProvider styletron={styletron}>
    <App/>
  </StyletronProvider>,
  document.getElementById('root')
);
```

This will instantiate your React app's Styletron instance with an empty stylesheet, which it will use to apply newly encountered declarations.

@rtsao, would it make sense to make the constructor argument optional?  I think the answer is no, since that could lead to implicit poor performance where StyletronClient silently re-adds a bunch of existing declarations to the DOM, but maybe I'm missing something.

**Comment by rtsao** [comment]
Yeah, maybe it's better for client-side use cases to have automatic creation of a stylesheet if one isn't passed into the constructor.

**Comment by sammkj** [comment]
@scott113341 I tried your suggestion. I still got the same error.

**Comment by rtsao** [comment]
@sammkj [The styletron client constructor expects a NodeList or HTMLCollection](http://styletron.js.org/StyletronClient.html). The following should work.

```js
const styleSheet = document.createElement('style');
document.head.appendChild(styleSheet);
const styletron = new Styletron([styleSheet]); // note the array literal here
```

**Comment by rtsao** [comment]
That said, I think it makes sense for a stylesheet to be optional. Styletron used to only use one stylesheet, so before it made sense to create it yourself and just pass it in. But now that it uses multiple sheets, I think this doesn't make as much sense.

**Comment by sammkj** [comment]
@rtsao ooppss. I admit that I didn't read the docs thoroughly. It's working now!

**Comment by vinnymac** [comment]
It would be nice to add a demo to the ReadMe like `styled-components` has. I adapted that one to use `styletron`. Check it [out](http://www.webpackbin.com/NkfzRwlQG).

**Comment by rtsao** [comment]
@vinnymac Nice! Added to the README 🎉

**Comment by rtsao** [comment]
Closing this issue in favor of https://github.com/rtsao/styletron/issues/34
