### ISSUE TITLE
Support taking react components

### ISSUE THREAD

**Issue by krainboltgreene** [rtsao/styletron#63]
It would be lovely to simply pass in a react component to `styled()` and have it automatically set the root element's classes.

**Comment by faddee** [comment]
I really wish for some kind of solution for this too. Having to nest your components with a styled element is really annoying and sometimes not even possible. E.g. you can't wrap a component which returns a `<li>` as root element if you want to provide styling for just that one.

I can't see any way of doing this automatically since there's no way we have any access to the root element inside React. Adding classnames to the root DOM element of the component is no option either. The best option is that the `styled`-function passes the generated classnames as prop to the specified component and then you have to manually set the `className` on the root element inside that component. That would work for me at least. Styled Components is [doing exactly this](https://github.com/styled-components/styled-components#third-party-components).

**Comment by faddee** [comment]
@rtsao is there any specific reason the `styled` function is restricted to only accept other styled components by Styletron as argument?

**Comment by rtsao** [comment]
I personally prefer the explicitness of a HOC interface in the case of third-party components, but passing className to third party components would work too. Since styled-components, does this now, I think it's a fair addition.

Thoughts on HOC vs passing className?

**Comment by faddee** [comment]
Sorry, but I believe it's a fairly unpleasant implementation detail that `styled` is restricted. Everything we would need is the `styled` function to accept tag name string and any component type. The `className` prop still needs to be handled manually by the component whether it's through a HoC interface or not. Having a HoC would be a nice additional option, and an easy one, for those who prefers that:

```js
function connectToStyles(styles) {
  return (Component) => styled(Component, styles);
}
```

**Comment by rtsao** [comment]
@faddee Good point about needing wrappers anyways to handle `className`. Also I do think a  HOC is sort of a footgun if you allow multiple classes to be returned due to atomic CSS (which is where the explicitness comes from).

The only thing I could think of would be something along the lines of like:

```js
const hoc = withStyles(() => ({
  color: 'red'
}), 'className');

const RedLink = hoc(Link);
```

I can see this being useful if you want flexibility on what prop the class name should be passed as.

But I guess this might as well just be:

```js
const RedLink = styled(Link, () => ({color: 'red'})); // defaults to `className`
const StyledAlt = styled(ThirdPary, () => ({color: 'red'}), 'altClassNameProp'); // use `altClassNameProp`
```

**Comment by rtsao** [comment]
Closed in https://github.com/rtsao/styletron/pull/64

**Comment by faddee** [comment]
Ok, I see where you're going. Should you support custom prop names like `modifiers.classes` too, like I've seen Airbnb been using? In this case I would handle it my self by simply wrapping it again:

```js
const classNameProxy(Component) {
  return props => <Component {...props} modifiers={{classes: props.className}} />
}

const Styled = styled(classNameProxy(ThirdPary), {color: 'red'});
```

It's not that pretty. But I don't think it will be needed that often and it's a better solution rather than having you covering all weird cases of deep objects and arrays etc. ☺️

**Comment by faddee** [comment]
Maybe this would be prettier:

```js
const Styled = styled(
  props => <ThirdPary {...props} modifiers={{classes: props.className}} />,
  {color: 'red'}
);
```

**Comment by faddee** [comment]
Oh, sorry. Just realized I missed the multiple classes part. Yeah, sure. A HoC with support with multiple classes sounds reasonable. But I like the purity of `styled` just supporting a single class.
