### ISSUE TITLE
[RFC] @keyframes and @font-face proposal

### ISSUE THREAD

**Issue by rtsao** [rtsao/styletron#92]
I'm still not sure about the API yet, but I was thinking it might look roughly something like the following:

### Additional instance methods on the core `Styletron` class
- `constructor()`
- `injectDeclaration(decl : object) -> string`
- `injectFontFace(font : object) -> string` (new)
  - returns name of injected font
- `injectKeyframes(keyframes : object) -> string` (new)
  - returns name of injected keyframe animation

**Core vs mixins**
Maybe these are in the core or maybe they are mixins. Probably some minor internal refactoring needed either way. Need to think about additional features that might be desired to see if a mixin interface is warranted.

**With media queries?**
There needs to be more investigation into nesting`@font-face` and `@keyframes` inside of media queries as this will affect the interface. The spec seems to disallow this, but apparently some browser support it?

**Naming/scoping?**
Should there be a way to manually set animation/keyframe names? I think they should just be sequential (`a`, `b`, `c`, etc) with an optional namespace (just like atomic declarations).

**Caching**
For declarations, there's only 4 properties with string values required to check equality. @font-face rules and @keyframes rules are much trickier. I think simple reference equality might be sufficient here, as typically these are defined separately. See below for why reference equality is probably OK in my opinion, as it's reasonable to expect these are hoisted outside of render.

### New primitives for `styletron-react` and friends

```js
// Note: just an idea...
const {styled, fontFace, keyframes} from 'styletron-react';

const myFont = fontFace({...fontProperties}); // no side effect
const myAnimation = keyframes({...keyframeProperties}); // no side effect

const Box = styled('div', {
  fontFamily: myFont, // injects once on first render 
  animationName: myAnimation // injects once on first render
});
```

**Comment by jbellsey** [comment]
Great to see movement on this!

I don’t love the idea of adding new magic to `styletron-react`, since we’ve written our own HoC to replace `styled`. I’d prefer having these features in one of the core libs.

I also wonder if tracking the new classes (e.g., `myFont` or `myAnimation`) is a feature that ought to be provided by styletron, rather than the app. These features are global by design. So one way or another, the application needs to give components a global cache, either on context, through a global store, or (see below) directly managed by styletron. These classes have zero likelihood of being manipulated in code -- they're set-and-forget -- which is why they might make sense to track in styletron:

```js
import {addFontFace, retrieveFontFace} from 'styletron-utils';

// at startup:
addFontFace(‘icons’, {...fontProperties});

// then:
const iconStyle = {
  fontSize: ‘12px’,
  fontFamily: retrieveFontFace(‘icons’)
};
```
Having the application keep track of globals is fine though; I wouldn't object if you said that's not the lib's role.

**Comment by faddee** [comment]
@jbellsey I agree that the new primitives for font face and keyframes would be better candidates for `styletron-utils`. But I prefer letting the app have ownership of its font faces and keyframes like the example @rtsao provided. Primarily because static type checkers like TypeScript wouldn't be able to warn me e.g. if I need to remove or rename a font face or keyframe. I would prefer exporting it from a module instead.

**Comment by rtsao** [comment]
Good point, indeed `fontFace` and `keyframes` have nothing to do with React. Agreed it definitely belongs in a lower-level library.

**Comment by ads1018** [comment]
Any update on the keyframe animation support? I think the biggest parity deficit between styletron and styled-components features is react native and keyframe animation support. Closing that gap would be awesome.

**Comment by rtsao** [comment]
I should get to this in the next few weeks. Happy to review/accept a PR for this though if anyone wants to give it a shot.

**Comment by aronallen** [comment]
Just some input here. What I love about styletron is that you don't explictly name anything, you just declare what you want. We did our own take on implementing @keyframes

```

{
  '@keyframes': [
  {'20%' : { background : 'red'}},
  {'100%' : { background : 'blue' }}
  ]
}

```

from this styletron would generate an animation name, and override the animation name property. Something similar could be done for @font-face.

**Comment by rtsao** [comment]
Closed in https://github.com/rtsao/styletron/pull/217
