### ISSUE TITLE
Publish rollup builds

### ISSUE THREAD

**Issue by rtsao** [rtsao/styletron#98]
- [ ] Convert from CommonJS to ES Modules everywhere
- [ ] Generate CommonJS and ES Module bundles with Rollup (also UMD?)

This will make tree shaking possible and solve a lot of issues with bloat and styletron-utils

**Comment by ludovicofischer** [comment]
I could give this a shot. What’s the main reason you would like ES6 modules? Step 1 could be partly achieved with https://github.com/nolanlawson/cjs-to-es6

**Comment by rtsao** [comment]
Two reasons:

1. We can publish "prebundled" modules with Rollup, which reduces [module overhead](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/) for consumers. So each package will just be a single file/module, rather than possibly multiple files/modules.
2. styletron-utils has lots of helper functions and whatnot, but if it is a CommonJS package, most bundles cannot tree shake unused portions. If a ES Module is also provided, webpack will be able to tree shake.

**Comment by ludovicofischer** [comment]
Hi, I’ve experimented with rollup builds (https://github.com/rtsao/styletron/compare/master...ludovicofischer:master).

Would you run the tests against the bundles or leave them as now?

Since we would need to use [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) for external dependencies anyway, it might be best to test the rollup build does not somehow break the published artifacts before converting the styletron code to ES6 modules.

**Comment by ludovicofischer** [comment]
I’d definitely say move to rollup and only _after_ convert to ES6 modules.

Since [bublé can’t transpile modules](https://buble.surge.sh/guide/#using-es-modules), if we concert the source to ES6 modules, then either the tests must use the bundled library or we must switch to Babel. Using the bundled library might not be ideal if you want to test functions that are not exported by the final bundle, but switching to Babel should be handled with some care.

On the other hand, just publishing a bundle should reduce module overhead. And solve https://github.com/rtsao/styletron/issues/77 since adding UMD should just be an additional line in the rollup config.
